### ISSUE TITLE
this lab made zero sense

### ISSUE THREAD

**Issue by minhl337** [learn-co-curriculum/traversing-nested-objects#24]
this lab made zero sense. it was poorly written and the information was not presented in an understandable format.

**Comment by rrcobb** [comment]
It sounds like this lesson was frustrating. If you have more specific feedback about the parts of the lesson that were confusing, we can try to address it.

**Comment by rrcobb** [comment]
From a slack conversation, here's a summary of what seemed frustrating - is this list correct?

- The Readme was very long
- There were too many comments in the functions
- More examples instead of just reading
- The comments were unclear if they were about above lines of code or below lines of code
- Could have used different names of the assigned variables

**Comment by sgharms** [comment]
@drakeltheryuujin 

Per @rrcobb 's points above let's see if we can add some clarification.

1. See if we can trim any points to get this smaller. We can't split it due to technical reasons.
2. I personally like the comments and believe reasonable people can disagree on whether it's a plus or minus.
3. [ACTION] While it won't shorten things up, see if we can add a few examples to punch things up.
4. [ACTION] Specify and ensure comments are placed consistently
5. [ACTION] Ensure variables are not repeated and / or are meaningfully named.

**Comment by drakeltheryuujin** [comment]
@sgharms I made a PR for this to try to make this more understandable. Let me know if It's ok to merge.
