### ISSUE TITLE
can't fork this lab

### ISSUE THREAD

**Issue by rslim87** [learn-co-curriculum/traversing-nested-objects#8]
![screen shot 2016-08-20 at 2 23 53 pm](https://cloud.githubusercontent.com/assets/19169421/17833080/07509ab4-66e2-11e6-922b-7a3dc31081c8.png)

As per my screen shot, it says fork this lab but there is no blue open button.  How can complete this lesson?

**Comment by throwawaythekey** [comment]
Came here to raise the same issue, which I've also raised on the non-canonical branch of this lesson tied to the track where I experienced the bug: learn-co-students/traversing-nested-objects-js-intro-000#3.

For users on the "Introduction to Javascript" track this lesson is being treated by the Learn.co site as a lab, rather than a readme. So the site wants you to fork and submit, even though there are no tests. The expected behavior would be that the site displays a "mark as read" button instead of fork/run/submit.

On further review, every issue that has been raised on this lesson has been about the same bug, but they keep getting closed. See issues #1, #2, #3, #4, #5, #6, #7. Note that both users who have posted screenshots demonstrating the bug are users viewing this lesson on the Intro to JS track.

Is the problem that this isn't the proper venue to report issues that derive from a lesson's integration with a particular track on the Learn.co site? i.e., that this lesson may be integrated properly for users of tracks other than "Intro to Javascript," and therefore the problem lies not with this lesson itself but with the site behavior? @AnnJohn, if this is the case, can you recommend an appropriate venue for raising this issue?

Also, attempting to fork this lab using `learn open traversing-nested-objects-js-intro-000` in the Learn IDE fails with "It looks like this lesson is a Readme. Plese open it in your browser." "Plese" should read "Please" in the given error message. What is the appropriate venue for logging this issue?

Thanks!

**Comment by AnnJohn** [comment]
hi @rslim87 thanks for raising this issue. We changed it from a lab to a Readme so this should be fine going forward now. Thanks!
